#markdown: rdiscount
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
highlighter: pygments
paginate: 8

safe:  false

#Site config
title: 休明的个人网站
description: 休明的个人网站
keywords: 任 休明
url: http://renxm.github.io
#url: http://localhost:4000
feed: /atom.xml
favicon: /images/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: renxm
    email: iamrzh艾特hotmail.com
    imageLink: http://tp3.sinaimg.cn/1769019670/180/40062948674/1
    simpleIntro: 我是「renxm」，这是我的网络ID，此处是这个虚拟人格的归宿。
    detailIntro:
      <p>此前的博客断断续续写了两三年，许久不更新后域名也过期了。</p>
      <p>此番赎回renxm.github.io这个永久域名，立志是要在网络上留下点痕迹的了。</p>

#Follow me
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/codeus
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/renxm
  - class: icon-twitter
    url: http://twitter.com/renxming
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 酷壳
      url: http://coolshell.cn/
    - text: 老赵
      url: http://blog.zhaojie.me/
    - text: 魏武挥
      url: http://weiwuhui.com/
    message: 常看的博客
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-53883855-1
googleAnaly:
  config: true
  id: UA-53883855-1

#comment config
disqus:
  config: true
  id: renxm
